# Generated by Django 5.0.1 on 2024-03-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_rename_project_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_link',
            new_name='demo',
        ),
    ]
