# Generated by Django 5.0.1 on 2024-03-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookapp',
            old_name='des',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='bookapp',
            old_name='category',
            new_name='password',
        ),
    ]
