# Generated by Django 5.0.1 on 2024-03-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_alter_project_album_alter_project_artist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Song',
        ),
    ]
